# Recreating the Mainz beam test

# These must be called before initialize
/remoll/setgeofile geometry_blackening/mollerMother_Mainz.gdml
/remoll/physlist/optical/enable

# This must be explicitly called
/run/initialize

/remoll/printgeometry true

#/remoll/scalefield map_directory/blockyHybrid_rm_3.0.txt 1.0
#/remoll/magcurrent map_directory/blockyHybrid_rm_3.0.txt 1000.0 A

# Raster and initial angle stuff
/remoll/oldras true
/remoll/rasx 5 mm
/remoll/rasy 5 mm

#Set Beam Generator settings
/remoll/evgen/set beam 
/run/beamOn 0


#----------------------------------------

#Setup for shooting photons on the cathode

#/remoll/evgen/beam/z -200
#/remoll/evgen/beam/x -1300 
#/remoll/evgen/beam/px -1
#/remoll/evgen/beam/py 0
#/remoll/evgen/beam/pz 0

#/remoll/evgen/beam/partName opticalphoton 

#/remoll/beamene 5 eV


#-----------------------------------------

# Make interactions with W, Cu, and Pb
# realistic rather than pure absorbers
/remoll/kryptonite/set true

/process/list

#/remoll/filename remollout_photons.root

#/run/beamOn 100

# Electrons incident on quartz------------

/remoll/evgen/beam/hitz 0 mm
/remoll/evgen/beam/hity 0 mm
/remoll/evgen/beam/hitx -987.5 mm
#/remoll/evgen/beam/theta -2.5 deg

/remoll/evgen/beam/zOffset 500 mm

/remoll/evgen/beam/partName e-

/remoll/filename remollout_quartz.root

/run/beamOn 1
